{% set name = "pyhumps" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyhumps-{{ version }}.tar.gz
  sha256: 498026258f7ee1a8e447c2e28526c0bea9407f9a59c03260aee4bd6c04d681a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}

test:
  imports:
    - humps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nficano/humps
  summary: Convert strings (and dictionary keys) between snake case, camel case and pascal case in Python.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - simstoykov
