{% set name = "pyhumps" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyhumps-{{ version }}.tar.gz
  sha256: 498026258f7ee1a8e447c2e28526c0bea9407f9a59c03260aee4bd6c04d681a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7

test:
  imports:
    - humps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nficano/humps
  summary: 🐫  Convert strings (and dictionary keys) between snake case, camel case and pascal case in Python. Inspired by Humps for Node
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - simstoykov
